server:
  port: 8080

spring:
  datasource:
    url : jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username : root
    password : root
    driverClassName : com.mysql.cj.jdbc.Driver
